name: sid
phase: train
gpu_ids:
  - 0
path:
  log: logs
  tb_logger: tb_logger
  results: results
  checkpoint: checkpoint
  resume_state: null
datasets:
  train:
    name: FFHQ
    datasetname: PairDataset
    data_args:
      datatype: mc
      dataroot:
        lq: /mnt/lustre/zhangyi1.vendor/data/Sony/pair_LH0.04s/input_crops/
        gt: /mnt/lustre/zhangyi1.vendor/data/Sony/pair_LH0.04s/target_crops/
      crop_size: 256
    dataroot: test
    batch_size: 32
    num_workers: 1
    use_shuffle: true
  val:
    name: CelebaHQ
    datasetname: PairDataset
    data_args:
      datatype: img
      dataroot:
        lq: ./dataset/Sony/test_LH0.04s/input/
        gt: ./dataset/Sony/test_LH0.04s/target/
      data_len: -1 # 2
      split: val
    mode: LRHR
    dataroot: test
model:
  which_model_G: ucdir
  unet_name: DY3h
  diffusion_name: ResiGaussianGuideDY
  finetune_norm: false
  unet:
    in_channel: 6
    out_channel: 3
    inner_channel: 64
    channel_mults:
      - 1
      - 2
      - 4
      - 8
      - 8
    attn_res:
      - 16
    res_blocks: 2
    dropout: 0.1
    norm_groups: 1
  beta_schedule:
    train:
      schedule: linear
      n_timestep: 2000
      linear_start: 0.000001
      linear_end: 0.01
    val:
      schedule: linear
      n_timestep: 200
      linear_start: 0.000001
      linear_end: 0.1
  diffusion:
    image_size: 128
    channels: 3
    conditional: true
train:
  n_iter: 500000
  val_freq: 20000
  save_checkpoint_freq: 10000
  save_models: 2000000
  print_freq: 2000
  optimizer:
    type: adamw
    lr: 0.0001
  ema_scheduler:
    use: true
    step_start_ema: 5000
    update_ema_every: 1
    ema_decay: 0.9999
wandb:
  project: sid-dist-bsu
